spring:
  profiles:
    active: yhly
---

server:
  port : 8080
spring:
  profiles: yhly
  application:
    name: yhlv-robticket
account:
  name: 
  pwd: 

---

server:
  port : 8081
spring:
  profiles: ssyg
  application:
    name: ssyg-robticket
account:
  name: 
  pwd: 
  
---

server:
  port : 8082
spring:
  profiles: yhfg
  application:
    name: yhfg-robticket
account:
  name: 
  pwd: 
